---
- hosts: go-api-service
  become: true
  tasks:
    - name: Init mongodb
      docker_container:
        name: mongodb
        image: "mongo:3.5-jessie"
        hostname: mongo
        networks:
          - name: "{{ go_network.name }}"
        volumes:
          - "{{ go.db_location }}:/data/db"
        pull: true
        restart_policy: always
        state: started
