version: '3'
services:

  db:
    image: mongo:3.6
    networks:
      - db_net
    volumes:
      - ~/mongodb/data:/data/db
    command: mongod --port 27028
    restart: unless-stopped

  api:
    build:
      context: ./backend/api
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    networks:
      - db_net
      - web_net
    volumes:
      - "$LDAP_CA_PATH:/usr/src/certs/ldapCA.crt:ro"
    depends_on:
      - db
    restart: unless-stopped

  service:
    build:
      context: ./backend/service
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    networks:
      - db_net
      - web_net
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build:
      context: ./frontend
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web_net
    volumes:
      - /etc/ssl/certs/company-ssl-certs:/etc/nginx/certs:ro
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx_filebeat/
    depends_on:
      - api
      - service
    restart: unless-stopped

  filebeat:
    hostname: go-service-production
    build:
      context: ./backend/filebeat
    volumes:
      - nginx_logs:/var/log/nginx/
    depends_on:
      - nginx
    restart: unless-stopped

volumes:
  nginx_logs:

networks:
  db_net:
    driver: bridge
  web_net:
    driver: bridge