version: '3.1'
services:

  db:
    image: mongo:3.6
    volumes:
      - ${MONGO_VOLUME_MOUNT}:/data/db
    networks:
      - database
    restart: unless-stopped

  api:
    build:
      context: ./backend/api
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    secrets:
      - ldap_ca_crt
      - jwt_secret
    environment:
      - MONGO_URI
      - LDAP_URI
      - LDAP_SEARCH_BASE
      - LDAP_USER_KEY
      - LDAP_EMAIL_DOMAIN
      - LDAP_ADMIN_KEY
      - LDAP_ADMIN_VALUE
    networks:
      - database
      - backend
    restart: unless-stopped

  service:
    build:
      context: ./backend/service
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    environment:
      - MONGO_URI
    networks:
      - database
      - backend
    restart: unless-stopped

  nginx:
    build:
      context: ./frontend
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    environment:
      - WEB_URL
    ports:
      - "80:80"
      - "443:443"
    volumes:

      - nginx_logs:/var/log/filebeat/
    secrets:
      - go_https_crt
      - go_https_key
    networks:
      - backend
    restart: unless-stopped

  backup:
    build:
      context: ./backend/backup
      args:
       - http_proxy
       - https_proxy
       - no_proxy
    environment:
      - MONGO_URI
      - BACKUP_URL
    secrets:
      - auth_header
    networks:
       - database

  filebeat:
    hostname: go-service-production
    build:
      context: ./backend/filebeat
    volumes:
      - nginx_logs:/var/log/nginx/
    environment:
      - LOGSTASH_HOSTS
    restart: unless-stopped

secrets:
  go_https_crt:
    file: ./.secrets/go_https_crt
  go_https_key:
    file: ./.secrets/go_https_key
  auth_header:
    file: ./.secrets/auth_header
  ldap_ca_crt:
    file: ./.secrets/ldap_ca_crt
  jwt_secret:
    file: ./.secrets/jwt_secret
volumes:
  nginx_logs:
networks:
  database:
  backend: