---
- hosts: localhost
  become: true
  tasks:
    - name: "Check so that the test setup has generated a new test_variables file."
      stat: path=./tests/test_variables
      register: present

    - name: "Fail if not present."
      fail: msg="The test_variables must exist!"
      when: present.stat.exists == False

    - name: Setup the environment
      include_vars:
        file: "tests/test_variables"

    - name: Add the tests.
      copy:
        src: ./tests/Go-API-Tests.postman_collection.json
        dest: "{{ go.home }}/tests/Go-API-Tests.postman_collection.json"
        owner: go
        group: sudo
        mode: "u=rw,g=r,o=r"

    - name: Setup the Postman container
      docker_container:
        name: newman_container
        image: "postman/newman_ubuntu1404:latest"
        hostname: newman
        networks:
          - name: "{{ go_network.name }}"
        volumes:
          - "{{ go.home }}/tests:/etc/newman"
        pull: true
        restart_policy: False
        state: started
        command: "run /etc/newman/Go-API-Tests.postman_collection.json --reporters=\"html,cli\" --reporter-html=\"go-api-result.html\""
