---
- hosts: localhost
  become: true
  tasks:
  - name: "Check so that the test setup has generated a new test_variables file."
    stat: path=./tests/test_variables
    register: present

  - name: "Fail if not present."
    fail: msg="The test_variables must exist!"
    when: present.stat.exists == False

  - name: Setup the environment
    include_vars:
      file: "tests/test_variables"

   # BEGINNING OF TEST REMOVAL 

  - name: Remove the API container
    docker_container:
      name: go-api
      keep_volumes: False
      force_kill: yes
      state: absent

  - name: Remove the Service container
    docker_container:
      name: go
      keep_volumes: False
      force_kill: yes
      state: absent

  - name: Remove the Mongo container
    docker_container:
      name: mongodb
      keep_volumes: False
      force_kill: yes
      state: absent

  - name: Remove the newman container
    docker_container:
      name: newman_container
      keep_volumes: False
      force_kill: yes
      state: absent

  - name: Remove the backend image
    docker_image:
      name: go-service
      state: absent
      force: yes

  - name: Remove test user.
    user:
      name: go
      state: absent
      force: yes

  - name: Remove the test network
    docker_network:
      name: "{{ go_network.name }}"
      state: absent
      force: yes

  - name: Remove the test variables
    file:
      path: tests/test_variables
      state: absent

  - name: Remove the test environment
    file:
      path: "{{ go.home }}"
      state: absent

    # END OF TEST SETUP
